// Import any icons we want to use here:
import '../icons/arrow.svg';
import '../icons/bubble.svg';
import '../icons/caret.svg';
import '../icons/clock.svg';
import '../icons/copy.svg';
import '../icons/cross.svg';
import '../icons/facebook.svg';
import '../icons/grid.svg';
import '../icons/instagram.svg';
import '../icons/linkedin.svg';
import '../icons/magnifying-glass.svg';
import '../icons/map-pin.svg';
import '../icons/menu.svg';
import '../icons/more.svg';
import '../icons/mouse.svg';
import '../icons/reload.svg';
import '../icons/tag.svg';
import '../icons/twitter.svg';
